name: BXARM on Linux

on:
  push:
  workflow_dispatch:

env:
  COMMON_DIR: /opt/iarsystems/bxarm-9.60.1/common/bin
  TARGET_DIR: /opt/iarsystems/bxarm-9.60.1/arm/bin

jobs:
  analyze:
    runs-on: fae-emea-lnx
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ichecks
        run: |
             $TARGET_DIR/ichecks --all --output cstat-checks.manifest 

      - name: icstat
        run: |
             $TARGET_DIR/icstat --db cstat.db --checks cstat-checks.manifest --sarif_dir sarif analyze -- $TARGET_DIR/iccarm main.c

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif/main.c.sarif
          category: cstat-analysis
